InteractiveAlpha/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('', include('backtest.urls')),
    path('chart/', include('chart.urls')),
    path('tools/', include('tools.urls')),
    path('optimize/', include('optimize.urls')),
]

backtest/urls.py
from django.urls import path
from . import views
from django.views.generic import ListView
from .models import Rule, Strategy
app_name = 'backtest'
urlpatterns = [
    path('',views.Index, name="index"),  
    path('backtest/strategies/load_list', views.LoadStrategyList, name='load_strategy_list'),
    path('backtest/strategies/add_strategy/', views.AddStrategy, name='add_strategy'),
    path('backtest/strategies/delete/<int:id_strategy>', views.DeleteStrategy, name='delete_strategy'),
    path('backtest/strategies/move/<int:id_strategy>', views.MoveStrategy, name='move_strategy'),
    path('backtest/strategies/managestrategy/<int:id>', views.DisplayStrategy, name='display'),
    path('strategy/<int:id_strategy>/export', views.ExportStrategy, name='export_strategy'),   
    path('backtest/strategies/managestrategy/modifygeneral/<int:id_strategy>', views.ModifyGeneralStrategy, name='modify_generalstrategy'),
    path('strategystate/<int:id_strategy>', views.Strategystate, name='strategystate'),
    path('get_strategy', views.ajax_get_strategy, name='get_strategy'),

    path('backtest/strategies/managestrategy/add_rule/<int:id_strategy>', views.AddRule, name='add_rule'),
    path('backtest/strategies/managestrategy/modify_rule/<int:id_rule>/<int:id_strategy>', views.ModifyRule, name='modify_rule'),
    path('rulestatus/<int:id_strategy>', views.Rulestatus, name='rulestatus'),
    path('ajax_get_rule/<int:id_strategy>', views.ajax_get_rules, name='get_rules'),
    path('getrule/<int:id_rulecombination>/<int:id_strategy>', views.ajax_get_rule, name='get_rule'),

    path('backtest/strategies/managestrategy/add_rulecombination/<int:id_strategy>', views.AddRuleCombination, name='add_rulecombination'),
    path('backtest/strategies/managestrategy/modify_rulecombination/<int:id_rulecombination>/<int:id_strategy>', views.ModifyRuleCombination, name='modify_rulecombination'),
    path('ajax_get_combination/<int:id_strategy>', views.ajax_get_combination_add, name='get_rule_combination_add'),
    path('ajax_get_combination/<int:id_rulecombination>/<int:id_strategy>', views.ajax_get_combination_modify, name='get_rule_combination_modify'),

    path('backtest/strategies/managestrategy/add_buyrule/<int:id_strategy>', views.AddBuyRule, name='add_buyrule'),
    path('backtest/strategies/managestrategy/add_sellrule/<int:id_strategy>', views.AddSellRule, name='add_sellrule'),   
    
    path('backtest/strategies/managestrategy/technical/<str:source>/<slug:indicator>$/add/<int:id_rule>/<int:id_strategy>', views.AddIndicator, name='add_indicator'),
    path('modifytechnical/<str:indicator>/<int:tech_id>/<int:id_strategy>/<str:requestfrom>/<int:requestrule>', views.ModifyIndicator, name='modifytechnical'),
    path('deletetechnical/<int:tech_id>/<int:id_strategy>/<str:requestfrom>/<int:requestrule>', views.DeleteIndicator, name='deletetechnical'),
    path('gettechnical', views.GetIndicator, name='gettechnical'),
    path('gettech/<int:id_rule>/<int:id_strategy>', views.ajax_get_tech, name='get_techs'),
    path('backtest/strategies/managestrategy/add_indicator_combination/<int:id_strategy>', views.AddIndicatorCombination, name="add_indicator_combination"),
    path('backtest/strategies/managestrategy/modify_indicator_combination/<int:id_comb>/<int:id_strategy>', views.ModifyIndicatorCombination, name="modify_combination"),
    path('backtest/get_techs/<int:id_comb>', views.GetTechs, name="get_techs_comb"),
    path('backtest/get_indicator_basic/<int:id_strategy>', views.GetIndicatorBasic, name="get_indicators_basic"),

    path('backtest/strategies/managestrategy/launchbacktest/<int:id_strategy>', views.LaunchBacktest, name='launchbacktest'),    
    path('launch_state', views.launch_state, name='launch_state'),
    path('backtest/strategies/displaystrategyresult/launchresult/<int:id_strategy>', views.launch_result, name='launch_result'),
    path('backtest/strategies/displaystrategyresult/<int:id_strategy>', views.ShowResult, name='showresult'),    
    
    path('delete/', views.Delete, name='delete'),

    path('backtest/', views.ManageBacktest, name="backtest"),
    path('backtest/strategies/',views.ManageStrategies, name="managestrategies"),
    path('backtest/strategies/managestrategy',views.ManageStrategy, name="managestrategy"),  
    path('backtest/strategies/displaystrategyresult',views.DisplayStrategyResult, name="displaystrategyresult"),

    path('backtest/strategies/add_category', views.AddCategory, name="add_category") ,
    path('backtest/strategies/rename_category', views.RenameCategory, name="rename_category") ,
    path('backtest/strategies/delete_category', views.DeleteCategory, name="delete_category") ,
    path('backtest/strategies/<int:id>',views.ManageCategory, name="managecategory"),
    path('backtest/strategies/default/', views.ManageDefaultStrategies, name="manage_default_strategies"),
    #Manage Combination Strategy
    path('backtest/comb_strategies/', views.ManageCombinationStrategies, name="manage_comb_strategies"),

    path('backtest/comb_strategies/<int:id_folder>/', views.CombManageStrategies, name="comb_manage_strategies"),
    path('backtest/comb_strategies/delete_strategy/<int:id_strategy>/', views.CombDeleteStrategy, name="comb_delete_strategy"),
    path('backtest/comb_get_tree_element/', views.ajax_comb_get_tree_element, name="comb_get_tree_element"),

    path('backtest/comb_strategies/manage/<int:id_strategy>/', views.CombManageStrategy, name="comb_manage_strategy"),
    path('backtest/comb_strategies/create_combination_strategy/', views.CombCreateCombStrategy, name="comb_create_comb_strategy"),
    path('backtest/comb_strategies/manage/modify_general/<int:id_comb_strategy>/',views.CombModifyGeneral, name="comb_modify_general"),
    path('backtest/comb_strategies/launch_strategy/<int:id_strategy>/',views.CombLaunchStrategy, name="comb_launch_strategy"),
    path('backtest/comb_strategies/launch_state/', views.CombLaunchState, name="comb_launch_state"),
    path('backtest/comb_strategies/manage_result/<int:id_strategy>/',views.CombLaunchResult, name="comb_launch_result"),
    path('backtest/comb_strategies/manage_result/', views.CombResults, name="comb_results"),
    path('backtest/comb_strategies/export_strategy/<int:id_folder>/<int:id_strategy>/', views.CombExportStrategy, name="comb_export_strategy"),
    path('backtest/comb_strategies/load_strategy/',views.CombLoadStrategy ,name="comb_load_strategy"),
    path('backtest/comb_strategies/manage/', views.CombManage, name="comb_strategy"),

    path('backtest/comb_strategies/create_folder/', views.CombCreateFolder, name="comb_create_folder"),
    path('backtest/comb_strategies/delete_folder/', views.CombDeleteFolder, name="comb_delete_folder"),

    path('backtest/comb_strategies/manage/add_strategy/<int:id_comb_strategy>/', views.CombAddStrategy, name="comb_add_strategy"),
    path('backtest/comb_strategies/manage/remove_strategy/', views.CombRemoveStrategy, name="comb_remove_strategy"),

    path('strategy_status/<int:id_comb>', views.CombStrategyStatus, name='strategy_status'),
]

chart/urls.py
from django.urls import path
from . import views
app_name = 'chart'
urlpatterns = [
    path('', views.view_chart, name="view_chart"),
    path('addChart', views.add_chart, name="add_chart"),
    path('removeChartList', views.remove_chart_list, name="remove_chart_list"),
    path('removeChart/<int:chart_id>', views.remove_chart, name="remove_chart"),
    path('addList/<int:chart_id>', views.add_list, name="add_list"),
    path('addList/<int:chart_id>/<int:list_id>/<str:f_name>', views.add_universe, name="add_universe"),
    path('addInstrument/<int:chart_id>/<int:list_id>/<str:f_name>', views.add_instrument, name="add_instrument"),
    path('getInstrument/', views.get_instrument, name="get_instrument"),
    path('viewInstrument/', views.view_instrument, name="view_instrument"),
    path('getModifyList/<int:chart_id>', views.get_modify_list, name="get_modify_list"),
    path('modifyChangeName/<int:list_id>/<int:chart_id>', views.modify_change_name, name="m_change_name"),
    path('modifyAddInstrument/<int:list_id>/<int:chart_id>', views.modify_add_instrument, name="m_add_instrument"),
    path('getDeleteInstruments/<int:list_id>/<int:chart_id>', views.get_delete_instruments, name="get_delete_instruments"),
    path('modifyDeleteInstruments/<int:instrument_id>/<int:chart_id>/<int:list_id>', views.m_delete_instrument, name="m_delete_instrument"),
    path('selectModifyMode/<int:list_id>/<int:chart_id>', views.select_modify_mode, name="select_modify_mode"),
    path('getDeleteList/<int:chart_id>', views.get_delete_list, name="get_delete_list"),
    path('DeleteList/<int:list_id>/<int:chart_id>', views.delete_list, name="delete_list"),
    path('writeJson', views.write_json, name="write_json"),
    path('update_chart_settings', views.update_chart_settings),
    path('update_overlay', views.update_overlay),
    path('update_indicator', views.update_indicator),
    path('delete_overlay/<int:chart_id>/<int:overlay_id>', views.delete_overlay),
    path('delete_indicator/<int:chart_id>/<int:indicator_id>', views.delete_indicator)
]

backtest/templates/backtest/strategies/add_category.html
{% extends "backtest/strategies/strategy_base.html" %}

{% load static %}

{% block content %}
<div class="table-container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-4">
            <form action="{% url 'backtest:add_category' %}" method="post">
                {% csrf_token %}
                <h2 class="strategy_title text-left">Add Folder</h2>
                <label>Name:</label>
                <input type="text" name="category_name" class="form-control" required>
                <label>Parent Folder:</label>
                <select class="form-control" name="parent_id" required>
                    <option value="0">Top level</option>
                    {% for category in categories %}
                    <option value="{{ category.id }}">{{category.path}}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="Add" class="btn btn-primary pull-right" style="margin-top: 30px" />
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
<script>
</script>
{% endblock content %}

backtest/templates/backtest/strategies/delete_category.html
{% extends "backtest/strategies/strategy_base.html" %}

{% load static %}

{% block content %}
<div class="table-container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-4">
            <form action="{% url 'backtest:delete_category' %}" method="post">
                {% csrf_token %}
                <h2 class="strategy_title text-left">Delete Folder</h2>
                <label>Select folder you are going to delete :</label>
                <select class="form-control" name="id" required>
                    {% for category in categories %}
                    <option value="{{ category.id }}">{{category.path}}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="Delete" class="btn btn-primary pull-right" style="margin-top: 30px" />
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
<script>

</script>
{% endblock content %}

backtest/templates/backtest/strategies/manage_default_strategies.html
{% extends "backtest/strategies/strategy_base.html" %}

{% load static %}

{% block content %}
<div class="table-container">
    <div class="displayoposite">
        <h4 class="strategy_title">{{title}}</h4>
    </div>
    <div class="btn-group flex-wrap" role="group">
        {# <a href="{% url 'backtest:rename_category' %}" class="btn btn-primary margin-right-5"> Rename Folder </a> #}
        <a href="{% url 'backtest:add_strategy' %}" class="btn btn-primary margin-right-5"> Add Strategy </a>
        <a href="{% url 'backtest:load_strategy_list' %}" class="btn btn-primary">Load Strategy </a>
    </div>
    <table class="table sortable" style="margin-top:10px">
        <tr>
            <th>Strategy</th>
            <th>StartDate</th>
            <th>EndDate</th>
            <th>Annual Return</th>
            <th>Sharpe Ratio</th>
            <th>Drowdown</th>
            {% if user.is_superuser %}
            <th>delete</th>
            <th>change folder</th>
            <th>export</th>            
            {% else %}
            <th>export</th>
            {% endif %}
        </tr>
        {% for strategy in strategies %}
        <tr>
            <td><a href="{% url 'backtest:display' id=strategy.id %}">{{strategy}}</a></td>
            <td><a href="{% url 'backtest:display' id=strategy.id %}">{{strategy.startdate}}</a></td>
            <td><a href="{% url 'backtest:display' id=strategy.id %}">{{strategy.enddate}}</a></td>
            <td><a href="{% url 'backtest:display' id=strategy.id %}">{{strategy.results.Annualized_return}}</a></td>
            <td><a href="{% url 'backtest:display' id=strategy.id %}">{{strategy.results.Sharpe_ratio}}</a></td>
            <td><a href="{% url 'backtest:display' id=strategy.id %}">{{strategy.results.Max_drawdown}}</a></td>
            {% if user.is_superuser %}
            <td><a href="{% url 'backtest:delete_strategy' id_strategy=strategy.id %}"><i class="fa fa-trash"
                        aria-hidden="true"></i> Delete </a></td>
            <td><a href="{% url 'backtest:move_strategy' id_strategy=strategy.id %}">Change</a></td>
            <td><a href="{% url 'backtest:export_strategy' id_strategy=strategy.id %}">Export</a></td>
            {% else %}
            <td><a href="{% url 'backtest:export_strategy' id_strategy=strategy.id %}">Export</a></td>
            {% endif %}
        </tr>
        {% empty %}
        <td>No Strategy!</td>
        {% endfor %}
    </table>
</div>
<script>
    var error_message = "{{error_message|safe}}"
    $(document).ready(function () {
        toastr.options = {
            'closeButton': true,
            'debug': false,
            'newestOnTop': false,
            'progressBar': false,
            'positionClass': 'toast-top-right',
            'preventDuplicates': false,
            'showDuration': '1000',
            'hideDuration': '1000',
            'timeOut': '5000',
            'extendedTimeOut': '1000',
            'showEasing': 'swing',
            'hideEasing': 'linear',
            'showMethod': 'fadeIn',
            'hideMethod': 'fadeOut',
        }
        if (error_message) {
            toastr.error('Not Empty Folder')
        }

    })
</script>
{% endblock %}

backtest/templates/backtest/strategies/manage_strategies.html
{% extends "backtest/strategies/strategy_base.html" %}

{% load static %}

{% block content %}
<div class="table-container">
    <div class="displayoposite">
        <h4 class="strategy_title">{{title}}</h4>
    </div>
    <div class="flex-wrap">
        {# <a href="{% url 'backtest:rename_category' %}" class="btn btn-primary margin-right-5"> Rename Folder </a> #}
        <a href="{% url 'backtest:add_strategy' %}" class="btn btn-primary margin-right-5"> Add Strategy </a>
        <a href="{% url 'backtest:load_strategy_list' %}" class="btn btn-primary">Load Strategy </a>
    </div>
    <table class="table sortable" style="margin-top:10px">
        <tr>
            <th>Strategy</th>
            <th>StartDate</th>
            <th>EndDate</th>
            <th>Annual Return</th>
            <th>Sharpe Ratio</th>
            <th>Drowdown</th>
            <th>delete</th>
            <th>change folder</th>
            <th>export</th>
        </tr>
        {% for strategy in strategies %}
        <tr>
            <td><a href="{% url 'backtest:display' id=strategy.id %}">{{strategy}}</a></td>
            <td><a href="{% url 'backtest:display' id=strategy.id %}">{{strategy.startdate}}</a></td>
            <td><a href="{% url 'backtest:display' id=strategy.id %}">{{strategy.enddate}}</a></td>
            <td><a href="{% url 'backtest:display' id=strategy.id %}">{{strategy.results.Annualized_return}}</a></td>
            <td><a href="{% url 'backtest:display' id=strategy.id %}">{{strategy.results.Sharpe_ratio}}</a></td>
            <td><a href="{% url 'backtest:display' id=strategy.id %}">{{strategy.results.Max_drawdown}}</a></td>
            <td><a href="{% url 'backtest:delete_strategy' id_strategy=strategy.id %}"><i class="fa fa-trash"
                        aria-hidden="true"></i> Delete </a></td>
            <td><a href="{% url 'backtest:move_strategy' id_strategy=strategy.id %}">Change</a></td>
            <td><a href="{% url 'backtest:export_strategy' id_strategy=strategy.id %}">Export</a></td>
        </tr>
        {% empty %}
        <td>No Strategy!</td>
        {% endfor %}
    </table>
</div>
<script>

</script>
{% endblock %}

backtest/templates/backtest/strategies/rename_category.html
{% extends "backtest/strategies/strategy_base.html" %}

{% load static %}

{% block content %}
<div class="table-container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-4">
            <form action="{% url 'backtest:rename_category' %}" method="post">
                {% csrf_token %}
                <h2 class="strategy_title text-left">Rename Folder</h2>
                <label>Select folder you are going to rename :</label>
                <select class="form-control" name="id" required>
                    {% for category in categories %}
                    <option value="{{ category.id }}">{{category.path}}</option>
                    {% endfor %}
                </select>
                <label>Name:</label>
                <input type="text" name="category_name" class="form-control" required>
                <input type="submit" value="Rename" class="btn btn-primary pull-right" style="margin-top: 30px" />
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
<script>
</script>
{% endblock content %}

backtest/templates/backtest/strategies/strategy_base.html
{% extends "backtest/backtest_base.html" %}

{% load static %}

{% block sidebar %}
<div class="navbar-button">
    <a href="{% url 'backtest:add_category' %}"><img src="{% static 'img/add.png' %}" width="30px" height="30px" /></a>
    <a href="{% url 'backtest:delete_category' %}"><img src="{% static 'img/delete.png' %}" width="30px"
            height="30px"></a>
</div>
<ul class="nav flex-column pl-1">
    <li class="nav-item">
        <h5><a href="{% url 'backtest:managecategory' id=0 %}">Strategy List</a></h5>
    </li>
    <div id="jstree-tree" class="well col-sm-3"></div>
</ul>
{% endblock %}

{% block mainnav %}
<nav class="navbar navbar-fixed-top navbar-toggleable-sm navbar-inverse bg-primary mb-3 customnavbacktest">
    <ul class="navbar-nav">
        <li class="nav-item text-center">
            <a class="nav-link customlinkbacktest menu_custom" href="{% url 'backtest:managestrategy' %}">Strategy</a>
        </li>
        <li class="nav-item text-center">
            <a class="nav-link customlinkbacktest menu_custom"
                href="{% url 'backtest:displaystrategyresult' %}">Results</a>
        </li>
    </ul>
</nav>
{% endblock %}
{% block subjs %}
<script>
    $(document).ready(function () {
        toastr.options = {
            'closeButton': true,
            'debug': false,
            'newestOnTop': false,
            'progressBar': true,
            'positionClass': 'toast-top-right',
            'preventDuplicates': false,
            'showDuration': '1000',
            'hideDuration': '1000',
            'timeOut': '5000',
            'extendedTimeOut': '1000',
            'showEasing': 'swing',
            'hideEasing': 'linear',
            'showMethod': 'fadeIn',
            'hideMethod': 'fadeOut',
        }
    })
    var tree_structure = "{{tree_structure|safe}}";
    if (tree_structure) {
        tree_structure = tree_structure.replace(/'/g, '"');
        tree_structure = JSON.parse(tree_structure)
        $('#jstree-tree')
            .on('select_node.jstree', function (e, data) {
                var objNode = data.instance.get_node(data.selected);
                if (objNode) {
                    $.ajax({
                        method: "GET",
                        url: "{% url 'backtest:get_strategy' %}",
                        data: {
                            "id": objNode.id
                        },
                        success: function (data) {
                            if (data.child_type == 2) {
                                var url = "{% url 'backtest:display' id=123 %}"
                                location.href = url.replace('123', data.child_id)
                            }
                            if (data.child_type == 1 && data.permission == 0) {
                                var url = "{% url 'backtest:managecategory' id=123 %}"
                                location.href = url.replace('123', data.child_id)
                            }
                            if (data.child_type == 1 && data.permission == 1) {
                                location.href = "{% url 'backtest:manage_default_strategies' %}"
                            }
                        }
                    })
                }
            })
            .jstree({
                core: {
                    data: tree_structure
                }
            });
    }
    var error_message = "{{error_message|safe}}"
    if (error_message) {
        toastr.error('Not Empty Folder')
    }

</script>
{% endblock %}