InteractiveAlpha/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('', include('backtest.urls')),
    path('chart/', include('chart.urls')),
    path('tools/', include('tools.urls')),
    path('optimize/', include('optimize.urls')),
]

chart/urls.py
from django.urls import path
from . import views
app_name = 'chart'
urlpatterns = [
    path('', views.view_chart, name="view_chart"),
    path('addChart', views.add_chart, name="add_chart"),
    path('removeChartList', views.remove_chart_list, name="remove_chart_list"),
    path('removeChart/<int:chart_id>', views.remove_chart, name="remove_chart"),
    path('addList/<int:chart_id>', views.add_list, name="add_list"),
    path('addList/<int:chart_id>/<int:list_id>/<str:f_name>', views.add_universe, name="add_universe"),
    path('addInstrument/<int:chart_id>/<int:list_id>/<str:f_name>', views.add_instrument, name="add_instrument"),
    path('getInstrument/', views.get_instrument, name="get_instrument"),
    path('viewInstrument/', views.view_instrument, name="view_instrument"),
    path('getModifyList/<int:chart_id>', views.get_modify_list, name="get_modify_list"),
    path('modifyChangeName/<int:list_id>/<int:chart_id>', views.modify_change_name, name="m_change_name"),
    path('modifyAddInstrument/<int:list_id>/<int:chart_id>', views.modify_add_instrument, name="m_add_instrument"),
    path('getDeleteInstruments/<int:list_id>/<int:chart_id>', views.get_delete_instruments, name="get_delete_instruments"),
    path('modifyDeleteInstruments/<int:instrument_id>/<int:chart_id>/<int:list_id>', views.m_delete_instrument, name="m_delete_instrument"),
    path('selectModifyMode/<int:list_id>/<int:chart_id>', views.select_modify_mode, name="select_modify_mode"),
    path('getDeleteList/<int:chart_id>', views.get_delete_list, name="get_delete_list"),
    path('DeleteList/<int:list_id>/<int:chart_id>', views.delete_list, name="delete_list"),
    path('writeJson', views.write_json, name="write_json"),
    path('update_chart_settings', views.update_chart_settings),
    path('update_overlay', views.update_overlay),
    path('update_indicator', views.update_indicator),
    path('delete_overlay/<int:chart_id>/<int:overlay_id>', views.delete_overlay),
    path('delete_indicator/<int:chart_id>/<int:indicator_id>', views.delete_indicator)
]

tools/urls.py
from django.urls import path
from . import views

app_name = 'tools'

urlpatterns = [

    path('', views.Index, name="index"),

    #UNIVERSES url
    path('universes/', views.ManageUniverses_default, name="manage_universes_default"),
    path('universes/create_folder/', views.CreateFolder, name="create_folder"),
    path('universes/delete_folder/', views.DeleteFolder, name="delete_folder"),
    path('universes/<int:id>', views.ManageUniverses, name="manage_universes"),

    path('universes/universe/', views.ManageUniverse_default, name="manage_universe_default"),
    path('universes/upload_universe/', views.UploadUniverse, name="upload_universe"),
    path('universe/delete_universe_default/', views.DeleteUniverse_default, name="delete_universe_default"),
    path('universe/add_instrument_default/<int:id>', views.AddInstrument_default, name="add_instrument_default"),
    path('universe/add_instrument_to_universe', views.AddInstrumenttoUniverse, name="add_instrument_to_universe"),
    path('universe/delete_instrument_default/<int:id>', views.DeleteInstrument_default, name="delete_instrument_default"),

    path('universes/create_universe/', views.CreateUniverse, name="create_universe"),
    path('universes/delete_universe/', views.DeleteUniverse, name="delete_universe"),
    path('universes/universe/<int:id>', views.ManageUniverse, name="manage_universe"),
    path('universes/universe/default/<int:id>', views.ManageDefaultUniverse, name="manage_default_universe"),

    path('universes/universe/add_instrument/<int:id>', views.AddInstrument, name="add_instrument"),
    # path('universes/universe/insert_instrument/', views.InsertInstrument, name="insert_instrument"),
    # path('universes/universe/update_instrument/', views.UpdateInstrument, name="update_instrument"),
    path('universes/universe/delete_instrument/', views.DeleteInstrument, name="delete_instrument"),

    path('universes/boolean_operation/', views.BooleanOperation, name="manage_boolean_operation"),

    path('universe/ajax_get_treeelement/', views.ajax_get_treeelement, name='ajax_get_treeelement'),
    path('universe/get_instrument_of_universe', views.ajax_get_instrument_of_universe, name="get_instrument_of_universe"), 


    #LISTS url
    path('lists/', views.LManageUniverses_default, name="lists_manage_universes_default"),
    path('lists/create_folder/', views.LCreateFolder, name="lists_create_folder"),
    path('lists/delete_folder/', views.LDeleteFolder, name="lists_delete_folder"),
    path('lists/<int:id>', views.LManageUniverses, name="lists_manage_universes"),

    path('lists/list/', views.LManageUniverse_default, name="lists_manage_universe_default"),
    path('lists/upload_universe/', views.LUploadUniverse, name="lists_upload_universe"),
    path('list/delete_universe_default/', views.LDeleteUniverse_default, name="lists_delete_universe_default"),
    path('list/add_instrument_default/<int:id>', views.LAddInstrument_default, name="lists_add_instrument_default"),
    path('list/add_instrument_to_universe', views.LAddInstrumenttoUniverse, name="lists_add_instrument_to_universe"),
    path('list/delete_instrument_default/<int:id>', views.LDeleteInstrument_default, name="lists_delete_instrument_default"),

    path('lists/create_universe/', views.LCreateUniverse, name="lists_create_universe"),
    path('lists/delete_universe/', views.LDeleteUniverse, name="lists_delete_universe"),
    path('lists/list/<int:id>', views.LManageUniverse, name="lists_manage_universe"),
    path('lists/list/default/<int:id>', views.LManageDefaultUniverse, name="lists_manage_default_universe"),

    path('lists/list/add_instrument/<int:id>', views.LAddInstrument, name="lists_add_instrument"),
    # path('universes/universe/insert_instrument/', views.InsertInstrument, name="lists_insert_instrument"),
    # path('universes/universe/update_instrument/', views.UpdateInstrument, name="lists_update_instrument"),
    path('lists/list/delete_instrument/', views.LDeleteInstrument, name="lists_delete_instrument"),

    path('lists/boolean_operation/', views.LBooleanOperation, name="lists_manage_boolean_operation"),

    path('list/ajax_get_treeelement/', views.Lajax_get_treeelement, name='lists_ajax_get_treeelement'),
    path('list/get_instrument_of_universe', views.Lajax_get_instrument_of_universe, name="lists_get_instrument_of_universe"),

    #BENCHMARKS url
    path('benchmarks/', views.BManageUniverses_default, name="benchmarks_manage_universes_default"),
    path('benchmarks/create_folder/', views.BCreateFolder, name="benchmarks_create_folder"),
    path('benchmarks/delete_folder/', views.BDeleteFolder, name="benchmarks_delete_folder"),
    path('benchmarks/<int:id>', views.BManageUniverses, name="benchmarks_manage_universes"),

    path('benchmarks/benchmark/', views.BManageUniverse_default, name="benchmarks_manage_universe_default"),
    path('benchmarks/upload_universe/', views.BUploadUniverse, name="benchmarks_upload_universe"),
    path('benchmark/delete_universe_default/', views.BDeleteUniverse_default, name="benchmarks_delete_universe_default"),
    path('benchmark/add_instrument_default/<int:id>', views.BAddInstrument_default, name="benchmarks_add_instrument_default"),
    path('benchmark/add_instrument_to_universe', views.BAddInstrumenttoUniverse, name="benchmarks_add_instrument_to_universe"),
    path('benchmark/delete_instrument_default/<int:id>', views.BDeleteInstrument_default, name="benchmarks_delete_instrument_default"),

    path('benchmarks/create_universe/', views.BCreateUniverse, name="benchmarks_create_universe"),
    path('benchmarks/delete_universe/', views.BDeleteUniverse, name="benchmarks_delete_universe"),
    path('benchmarks/benchmark/<int:id>', views.BManageUniverse, name="benchmarks_manage_universe"),
    path('benchmarks/benchmark/default/<int:id>', views.BManageDefaultUniverse, name="benchmarks_manage_default_universe"),

    path('benchmarks/benchmark/add_instrument/<int:id>', views.BAddInstrument, name="benchmarks_add_instrument"),
    # path('universes/universe/insert_instrument/', views.InsertInstrument, name="benchmarks_insert_instrument"),
    # path('universes/universe/update_instrument/', views.UpdateInstrument, name="benchmarks_update_instrument"),
    path('benchmarks/benchmark/delete_instrument/', views.BDeleteInstrument, name="benchmarks_delete_instrument"),

    path('benchmark/ajax_get_treeelement/', views.Bajax_get_treeelement, name='benchmarks_ajax_get_treeelement'),
    path('benchmark/get_instrument_of_universe', views.Bajax_get_instrument_of_universe, name="benchmarks_get_instrument_of_universe"),

    #RANKING URL
    path('ranksystems/', views.RManageRankSystems, name="rank_manage_rank_systems"),
    path('ranksystems/<int:parent_id>', views.RManageRankSystems_folder, name="rank_manage_rank_systems_folder"),
    path('ranksystems/add_ranking_system/', views.RAddRankSystem, name="rank_add_ranking_system"),
    path('ranksystems/delete_ranking_system/<int:id>',views.RDeleteRankingSystem, name="rank_delete_ranking_system"),
    path('ranksystems/export/<int:id_rank_system>/<int:id_parent>', views.RExportRankingSystem, name="rank_export_ranking_system"),
    path('ranksystems/load_ranking_system/', views.RLoadRankingSystem, name="rank_load_ranking_system"),
    path('ranksystems/manage_ranking_system/<int:id>',views.RManageRankingSystem, name="rank_manage_ranking_system"),
    path('ranksystems/manage_rank_get_data/', views.RGetRankData, name="rank_get_data"),

    path('ranksystems/add_ranking_rule/<int:id>',views.RAddRankingRule, name="rank_add_ranking_rule"),
    path('ranksystems/modify_ranking_rule/<int:id_rank>/<int:id_rule>', views.RModifyRule, name="rank_modify_rule"),
    path('ranksystem/get_indicator/<int:id_rule>/<int:id_rank>', views.ajax_get_tech, name='rank_get_tech'),
    path('ranksystem/delete_rule/', views.RDeleteRule, name="rank_delete_rule"),

    path('ranksystems/add_indicator/<str:source>/<slug:indicator>$/add/<int:id_rank>', views.RAddIndicator, name='rank_add_indicator'),
    path('ranksystems/rank_get_indicator/<int:id_rank>', views.RGetIndicator, name="rank_get_indicator"),
    path('ranksystems/rank_get_indicator_add', views.RGetIndicatorAdd, name="rank_get_indicator_add"),
    path('ranksystems/modifytechnical/<str:indicator>/<int:tech_id>/<int:id_rank>/<str:requestfrom>/<int:requestrule>', views.RModifyIndicator, name='rank_modifytechnical'),
    path('ranksystems/deletetechnical/<int:tech_id>/<int:id_rank>/<str:requestfrom>/<int:requestrule>', views.RDeleteIndicator, name='rank_deletetechnical'),

    path('ranksystems/add_indicator_combination/<int:id>', views.RAddIndicatorCombination, name="rank_add_indicator_combination"),
    path('ranksystems/modify_indicator_combination/<int:id_comb>/<int:id_system>', views.RModifyIndicatorCombination, name="rank_modify_combination"),
    path('ranksystems/get_techs_comb/<int:id_comb>', views.RGetTechs, name="rank_get_techs_comb"),
    path('ranksystems/get_indicator_basic/<int:id_system>', views.RGetIndicatorBasic, name="rank_get_indicators_basic"),

    path('ranksystems/createfolder/', views.RCreateFolder, name="rank_create_folder"),
    path('ranksystems/deletefolder/', views.RDeleteFolder, name='rank_delete_folder'),

    path('ranksystems/default/', views.RManageDefaultSystems, name="rank_manage_default_systems"),

    #LIQUIDITY URL
    path('liquiditysystems/', views.LSManageLiquiditySystems, name="liqudity_manage_liquidity_systems"),
    path('liquiditysystems/<int:parent_id>', views.LSManageLiquiditySystems_folder, name="liquidity_manage_liquidity_system_folder"),
    path('liquiditysystems/add_liquidity_system/', views.LSAddLiquiditySystem, name="liquidity_add_liquidity_system"),
    path('liquiditysystems/export/<int:id_system>/<int:id_parent>', views.LSExportLiquiditySystem, name="liquidity_export_liquidity_system"),

tools/forms.py
from django import forms

from .models import Universe_Default, Lists_Default, Benchmarks_Default, Ranking_System, Ranking_Rule, Liquidity_System, Liquidity_Rule
                    # Indicators_Combination, Indicators_Combination_System

class UniverseForm(forms.ModelForm):
    class Meta:
        model = Universe_Default
        fields = ('file',)

class ListForm(forms.ModelForm):
    class Meta:
        model = Lists_Default
        fields = ('file',)

class BenchmarkForm(forms.ModelForm):
    class Meta:
        model = Benchmarks_Default
        fields = ('file',)

class RankingSystemForm(forms.ModelForm):
    class Meta:
        model = Ranking_System
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }
        def clean(self):
            cleaned_data = super(RankingSystemForm, self).clean()           
            return cleaned_data 

class RankingRuleForm(forms.ModelForm):
    class Meta:
        model = Ranking_Rule
        fields = '__all__'
        exclude = ('rank_id',)
        widgets = {
            'weight': forms.NumberInput(attrs={'class':'form-control'}),
            'indicator': forms.TextInput(attrs={'class':'form-control','id':'indicator'}),
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'direction': forms.Select(attrs={'class':'form-control'}),
        }
        def clean(self):
            cleaned_data = super(RankingRuleForm, self).clean()           
            return cleaned_data 

#LIQUIDITY SYSTEM
class LiquiditySystemForm(forms.ModelForm):
    class Meta:
        model = Liquidity_System
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }
        def clean(self):
            cleaned_data = super(LiquiditySystemForm, self).clean()           
            return cleaned_data 

class LiquidityRuleForm(forms.ModelForm):
    class Meta:
        model = Liquidity_Rule
        fields = '__all__'
        widgets = {
            'min_amount': forms.NumberInput(attrs={'class':'form-control'}),
            'max_amount': forms.NumberInput(attrs={'class':'form-control'}),
            'rule': forms.TextInput(attrs={'class':'form-control', 'id':'liquidity_rule'}),
            'name': forms.TextInput(attrs={'class':'form-control'}),
        }
        def clean(self):
            cleaned_data = super(LiquidityRuleForm, self).clean()           
            return cleaned_data 

tools/templates/tools/benchmarks/add_instrument.html
{% extends "tools/benchmarks/base_universes.html" %}

{% block content %}
<div class="table-container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-4">
            <form action="{% url 'tools:benchmarks_add_instrument' id=universe.id %}" method="post">
                {% csrf_token %}
                <h2 class="strategy_title text-left">Add Instrument</h2>
                <label>Symbol:</label>
                <input type="text" name="symbol" class="form-control" required>
                <label>Name:</label>
                <input type="text" name="name" class="form-control" required>
                <input type="submit" value="Add" class="btn btn-primary pull-right" style="margin-top: 30px" />
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>

{% endblock %}

tools/templates/tools/benchmarks/base_universes.html
{% extends "tools/base_tools.html" %}

{% load static %}

{% block subcss %}
<link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" />
<link rel="stylesheet" href="//use.fontawesome.com/releases/v5.6.3/css/all.css" />
<link rel="stylesheet" href="//unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.css" />
<link type="text/css" href="//gyrocode.github.io/jquery-datatables-checkboxes/1.2.11/css/dataTables.checkboxes.css"
    rel="stylesheet" />
{% endblock %}

{% block sidebar %}
<ul class="nav flex-column pl-1">
    <div class="navbar-button">
        <a href="{% url 'tools:benchmarks_create_folder' %}"><img src="{% static 'img/add.png' %}" width="30px" height="30px"
                title="Create Folder" /></a>
        <a href="{% url 'tools:benchmarks_delete_folder' %}"><img src="{% static 'img/delete.png' %}" width="30px" height="30px"
                title="Delete Folder"></a>
    </div>
    <li class="nav-item">
        <h5><a href="{% url 'tools:benchmarks_manage_universes' id=0 %}">Benchmark Structure</a></h5>
    </li>
    <div id="jstree-tree" class="well col-sm-3"></div>
</ul>
{% endblock %}

{% block mainnav %}

{% endblock %}

{% block subjs %}
<script>
    var tree_structure = "{{tree_structure|safe}}";
    tree_structure = tree_structure.replace(/'/g, '"');
    tree_structure = JSON.parse(tree_structure)

    $('#jstree-tree')
        .on('select_node.jstree', function (e, data) {
            var objNode = data.instance.get_node(data.selected);
            if (objNode) {
                $.ajax({
                    method: "GET",
                    url: "{% url 'tools:benchmarks_ajax_get_treeelement' %}",
                    data: {
                        "id": objNode.id
                    },
                    success: function (data) {
                        if (data.child_type == 2 && data.permission == 0) {
                            var url = "{% url 'tools:benchmarks_manage_universe' id=123 %}"
                            location.href = url.replace('123', data.child_id)
                        }
                        else if (data.child_type == 2 && data.permission == 1) {
                            var url = "{% url 'tools:benchmarks_manage_default_universe' id=123 %}"
                            location.href = url.replace('123', data.child_id)
                        }
                        else if (data.child_type == 1 && data.permission == 0) {
                            var url = "{% url 'tools:benchmarks_manage_universes' id=123 %}"
                            location.href = url.replace('123', data.child_id)
                        }
                        else if (data.child_type == 1 && data.permission == 1) {
                            location.href = "{% url 'tools:benchmarks_manage_universes_default' %}"
                        }
                    }
                })
            }
        })
        .jstree({
            core: {
                data: tree_structure
            }
        });
</script>
<script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<script src="//unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.js"></script>
<script type="text/javascript"
    src="//gyrocode.github.io/jquery-datatables-checkboxes/1.2.11/js/dataTables.checkboxes.min.js"></script>
{% endblock %}

tools/templates/tools/benchmarks/manage_universe_default.html
{% extends "tools/benchmarks/base_universes.html" %}

{% block content %}
{% if not error_message %}
<div class="table-container">
    <div class="displayoposite">
        <h4 class="strategy_title">{{universe.title}}</h4>
    </div>
    {% if user.is_superuser %}
    <a href="#" class="btn btn-primary margin-right-5 " data-toggle="modal" data-target="#myModal_add">
        Add Instrument
    </a>
    {% endif %}
    <table id="example" class="table table-striped table-bordered" style="width:100%;margin-top:10px">
        <thead>
            <tr>
                <th>Symbol</th>
                <th>Name</th>
                {% if user.is_superuser%}
                <th>Delete</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for instrument in instruments %}
            <tr>
                <td>{{instrument.0}}</td>
                <td>{{instrument.1}}</td>
                {% if user.is_superuser%}
                <td><a class="danger remove confirm-delete" href="#" data-toggle="modal" data-target="#myModal"
                        data-symbol="{{instrument.0}}" title="Delete">
                        <i class="fa fa-trash"></i>Delete
                    </a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
<div id="myModal" class="modal fade" role="dialog">
    <form method="post" action="{% url 'tools:benchmarks_delete_instrument_default' id=universe.id %}">
        {% csrf_token %}
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-body">
                    <h5 class="modal-title">Are you sure you want to delete?</h5>
                    <input type="hidden" name="symbol" id="delete_symbol" />
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Delete</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </form>
</div>
<div id="myModal_add" class="modal fade" role="dialog">
    <form method="post" action="{% url 'tools:benchmarks_add_instrument_default' id=universe.id %}">
        {% csrf_token %}
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h3>Add to Benchmark</h3>
                </div>
                <div class="modal-body">
                    <label>Symbol: </label>
                    <input type="text" class="form-control" name="symbol" />
                    <label>Name: </label>
                    <input type="text" class="form-control" name="name" />
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Add</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    var token = '{{csrf_token}}';
    var selectedInstrument = []
    var table = $('#table_operation');
    $(document).ready(function () {
        $('#example').DataTable();
        $(document).on("click", ".confirm-delete", function () {
            $("#delete_symbol").val($(this).data('symbol'));
        })
    });

</script>
{% else %}

{% endif %}
{% endblock %}

tools/templates/tools/benchmarks/manage_universes.html
{% extends "tools/benchmarks/base_universes.html" %}

{% block content %}
<div class="table-container">
    {% if top_folder %}
    <div class="displayoposite">
        <h4 class="strategy_title">{{title}}</h4>
    </div>
    <div class="btn-group flex-wrap" role="group">
        {# <a href="{% url 'backtest:rename_category' %}" class="btn btn-primary margin-right-5"> Rename Folder </a> #}
        <a href="{% url 'tools:benchmarks_create_universe' %}" class="btn btn-primary margin-right-5">Create Benchmark </a>
        {% if user.is_superuser and top_folder %}
        <a href="#" class="btn btn-primary margin-right-5 js-upload-photos"><span class="fa fa-upload"></span>
            Load Default Benchmark </a>        
        <input id="fileupload" type="file" name="file" multiple style="display: none;"
            data-url="{% url 'tools:benchmarks_upload_universe' %}" data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
        {% endif %}
    </div>
    <table class="table sortable" style="margin-top:10px">
        <tr>
            <th>Name</th>
            <th>Number of Instruments</th>
            {% if user.is_superuser%}
            <th>Delete</th>
            {% endif %}
        </tr>
        {% for universe in universe_lists %}
        <tr>
            <td><a href="{% url 'tools:benchmarks_manage_default_universe' id=universe.id %}">{{universe.title}}</a></td>
            <td>{{universe.count}}</td>
            {% if user.is_superuser%}
            <td><a href="#" class="confirm-delete"
                    data-toggle="modal" data-target="#myModal" data-id="{{universe.id}}"><i class="fa fa-trash"
                        aria-hidden="true"></i> Delete </a></td>
            {%  endif %}
        </tr>
        {% empty %}
        <td>No Benchmark!</td>
        {% endfor %}
    </table>
</div>
<div id="myModal" class="modal fade" role="dialog">
    <form method="post" action="{% url 'tools:benchmarks_delete_universe_default' %}">
        {% csrf_token %}
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-body">
                    <h5 class="modal-title">Are you sure you want to delete?</h5>
                    <input type="hidden" name="id" id="deleteid" />
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Delete</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Uploading...</h4>
            </div>
            <div class="modal-body">
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="displayoposite">
    <h4 class="strategy_title">{{title}}</h4>
</div>
<div class="btn-group flex-wrap" role="group">
    {# <a href="{% url 'backtest:rename_category' %}" class="btn btn-primary margin-right-5"> Rename Folder </a> #}
    <a href="{% url 'tools:benchmarks_create_universe' %}"
        class="btn btn-primary margin-right-5 {% if not user.is_superuser and top_folder %}disabled{% endif %}">
        Create Benchmark </a>
    {#<a href="#" class="btn btn-primary margin-right-5 js-upload-photos" {% if not user.is_superuser and top_folder %} style="display: none;" {% endif %}> Load Benchmark </a>#}
    <input id="fileupload" type="file" name="file" multiple style="display: none;"
        data-url="{% url 'tools:benchmarks_upload_universe' %}" data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

</div>
<table class="table sortable" style="margin-top:10px">
    <tr>
        <th>Name</th>
        <th>Number of Instruments</th>
        <th>Delete</th>
    </tr>
    {% for universe in universe_lists %}
    <tr>
        <td><a href="{% url 'tools:benchmarks_manage_universe' id=universe.id %}">{{universe}}</a></td>
        <td>{{universe.count}}</td>
        <td><a href="#" class="confirm-delete {% if not user.is_superuser and top_folder %}disabled{% endif %}"
                data-toggle="modal" data-target="#myModal" data-id="{{universe.id}}"><i class="fa fa-trash"
                    aria-hidden="true"></i> Delete </a></td>
    </tr>
    {% empty %}
    <td>No Benchmark!</td>
    {% endfor %}
</table>
</div>
<div id="myModal" class="modal fade" role="dialog">
    <form method="post" action="{% url 'tools:benchmarks_delete_universe' %}">
        {% csrf_token %}
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-body">
                    <h5 class="modal-title">Are you sure you want to delete?</h5>
                    <input type="hidden" name="id" id="deleteid" />
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Delete</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Uploading...</h4>
            </div>
            <div class="modal-body">
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}

<script>
    $(document).ready(function () {
        $(document).on("click", ".confirm-delete", function () {
            $("#deleteid").val($(this).data('id'))
        });
    });
</script>
{% endblock %}