InteractiveAlpha/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('', include('backtest.urls')),
    path('chart/', include('chart.urls')),
    path('tools/', include('tools.urls')),
    path('optimize/', include('optimize.urls')),
]

backtest/urls.py
from django.urls import path
from . import views
from django.views.generic import ListView
from .models import Rule, Strategy
app_name = 'backtest'
urlpatterns = [
    path('',views.Index, name="index"),  
    path('backtest/strategies/load_list', views.LoadStrategyList, name='load_strategy_list'),
    path('backtest/strategies/add_strategy/', views.AddStrategy, name='add_strategy'),
    path('backtest/strategies/delete/<int:id_strategy>', views.DeleteStrategy, name='delete_strategy'),
    path('backtest/strategies/move/<int:id_strategy>', views.MoveStrategy, name='move_strategy'),
    path('backtest/strategies/managestrategy/<int:id>', views.DisplayStrategy, name='display'),
    path('strategy/<int:id_strategy>/export', views.ExportStrategy, name='export_strategy'),   
    path('backtest/strategies/managestrategy/modifygeneral/<int:id_strategy>', views.ModifyGeneralStrategy, name='modify_generalstrategy'),
    path('strategystate/<int:id_strategy>', views.Strategystate, name='strategystate'),
    path('get_strategy', views.ajax_get_strategy, name='get_strategy'),

    path('backtest/strategies/managestrategy/add_rule/<int:id_strategy>', views.AddRule, name='add_rule'),
    path('backtest/strategies/managestrategy/modify_rule/<int:id_rule>/<int:id_strategy>', views.ModifyRule, name='modify_rule'),
    path('rulestatus/<int:id_strategy>', views.Rulestatus, name='rulestatus'),
    path('ajax_get_rule/<int:id_strategy>', views.ajax_get_rules, name='get_rules'),
    path('getrule/<int:id_rulecombination>/<int:id_strategy>', views.ajax_get_rule, name='get_rule'),

    path('backtest/strategies/managestrategy/add_rulecombination/<int:id_strategy>', views.AddRuleCombination, name='add_rulecombination'),
    path('backtest/strategies/managestrategy/modify_rulecombination/<int:id_rulecombination>/<int:id_strategy>', views.ModifyRuleCombination, name='modify_rulecombination'),
    path('ajax_get_combination/<int:id_strategy>', views.ajax_get_combination_add, name='get_rule_combination_add'),
    path('ajax_get_combination/<int:id_rulecombination>/<int:id_strategy>', views.ajax_get_combination_modify, name='get_rule_combination_modify'),

    path('backtest/strategies/managestrategy/add_buyrule/<int:id_strategy>', views.AddBuyRule, name='add_buyrule'),
    path('backtest/strategies/managestrategy/add_sellrule/<int:id_strategy>', views.AddSellRule, name='add_sellrule'),   
    
    path('backtest/strategies/managestrategy/technical/<str:source>/<slug:indicator>$/add/<int:id_rule>/<int:id_strategy>', views.AddIndicator, name='add_indicator'),
    path('modifytechnical/<str:indicator>/<int:tech_id>/<int:id_strategy>/<str:requestfrom>/<int:requestrule>', views.ModifyIndicator, name='modifytechnical'),
    path('deletetechnical/<int:tech_id>/<int:id_strategy>/<str:requestfrom>/<int:requestrule>', views.DeleteIndicator, name='deletetechnical'),
    path('gettechnical', views.GetIndicator, name='gettechnical'),
    path('gettech/<int:id_rule>/<int:id_strategy>', views.ajax_get_tech, name='get_techs'),
    path('backtest/strategies/managestrategy/add_indicator_combination/<int:id_strategy>', views.AddIndicatorCombination, name="add_indicator_combination"),
    path('backtest/strategies/managestrategy/modify_indicator_combination/<int:id_comb>/<int:id_strategy>', views.ModifyIndicatorCombination, name="modify_combination"),
    path('backtest/get_techs/<int:id_comb>', views.GetTechs, name="get_techs_comb"),
    path('backtest/get_indicator_basic/<int:id_strategy>', views.GetIndicatorBasic, name="get_indicators_basic"),

    path('backtest/strategies/managestrategy/launchbacktest/<int:id_strategy>', views.LaunchBacktest, name='launchbacktest'),    
    path('launch_state', views.launch_state, name='launch_state'),
    path('backtest/strategies/displaystrategyresult/launchresult/<int:id_strategy>', views.launch_result, name='launch_result'),
    path('backtest/strategies/displaystrategyresult/<int:id_strategy>', views.ShowResult, name='showresult'),    
    
    path('delete/', views.Delete, name='delete'),

    path('backtest/', views.ManageBacktest, name="backtest"),
    path('backtest/strategies/',views.ManageStrategies, name="managestrategies"),
    path('backtest/strategies/managestrategy',views.ManageStrategy, name="managestrategy"),  
    path('backtest/strategies/displaystrategyresult',views.DisplayStrategyResult, name="displaystrategyresult"),

    path('backtest/strategies/add_category', views.AddCategory, name="add_category") ,
    path('backtest/strategies/rename_category', views.RenameCategory, name="rename_category") ,
    path('backtest/strategies/delete_category', views.DeleteCategory, name="delete_category") ,
    path('backtest/strategies/<int:id>',views.ManageCategory, name="managecategory"),
    path('backtest/strategies/default/', views.ManageDefaultStrategies, name="manage_default_strategies"),
    #Manage Combination Strategy
    path('backtest/comb_strategies/', views.ManageCombinationStrategies, name="manage_comb_strategies"),

    path('backtest/comb_strategies/<int:id_folder>/', views.CombManageStrategies, name="comb_manage_strategies"),
    path('backtest/comb_strategies/delete_strategy/<int:id_strategy>/', views.CombDeleteStrategy, name="comb_delete_strategy"),
    path('backtest/comb_get_tree_element/', views.ajax_comb_get_tree_element, name="comb_get_tree_element"),

    path('backtest/comb_strategies/manage/<int:id_strategy>/', views.CombManageStrategy, name="comb_manage_strategy"),
    path('backtest/comb_strategies/create_combination_strategy/', views.CombCreateCombStrategy, name="comb_create_comb_strategy"),
    path('backtest/comb_strategies/manage/modify_general/<int:id_comb_strategy>/',views.CombModifyGeneral, name="comb_modify_general"),
    path('backtest/comb_strategies/launch_strategy/<int:id_strategy>/',views.CombLaunchStrategy, name="comb_launch_strategy"),
    path('backtest/comb_strategies/launch_state/', views.CombLaunchState, name="comb_launch_state"),
    path('backtest/comb_strategies/manage_result/<int:id_strategy>/',views.CombLaunchResult, name="comb_launch_result"),
    path('backtest/comb_strategies/manage_result/', views.CombResults, name="comb_results"),
    path('backtest/comb_strategies/export_strategy/<int:id_folder>/<int:id_strategy>/', views.CombExportStrategy, name="comb_export_strategy"),
    path('backtest/comb_strategies/load_strategy/',views.CombLoadStrategy ,name="comb_load_strategy"),
    path('backtest/comb_strategies/manage/', views.CombManage, name="comb_strategy"),

    path('backtest/comb_strategies/create_folder/', views.CombCreateFolder, name="comb_create_folder"),
    path('backtest/comb_strategies/delete_folder/', views.CombDeleteFolder, name="comb_delete_folder"),

    path('backtest/comb_strategies/manage/add_strategy/<int:id_comb_strategy>/', views.CombAddStrategy, name="comb_add_strategy"),
    path('backtest/comb_strategies/manage/remove_strategy/', views.CombRemoveStrategy, name="comb_remove_strategy"),

    path('strategy_status/<int:id_comb>', views.CombStrategyStatus, name='strategy_status'),
]

chart/urls.py
from django.urls import path
from . import views
app_name = 'chart'
urlpatterns = [
    path('', views.view_chart, name="view_chart"),
    path('addChart', views.add_chart, name="add_chart"),
    path('removeChartList', views.remove_chart_list, name="remove_chart_list"),
    path('removeChart/<int:chart_id>', views.remove_chart, name="remove_chart"),
    path('addList/<int:chart_id>', views.add_list, name="add_list"),
    path('addList/<int:chart_id>/<int:list_id>/<str:f_name>', views.add_universe, name="add_universe"),
    path('addInstrument/<int:chart_id>/<int:list_id>/<str:f_name>', views.add_instrument, name="add_instrument"),
    path('getInstrument/', views.get_instrument, name="get_instrument"),
    path('viewInstrument/', views.view_instrument, name="view_instrument"),
    path('getModifyList/<int:chart_id>', views.get_modify_list, name="get_modify_list"),
    path('modifyChangeName/<int:list_id>/<int:chart_id>', views.modify_change_name, name="m_change_name"),
    path('modifyAddInstrument/<int:list_id>/<int:chart_id>', views.modify_add_instrument, name="m_add_instrument"),
    path('getDeleteInstruments/<int:list_id>/<int:chart_id>', views.get_delete_instruments, name="get_delete_instruments"),
    path('modifyDeleteInstruments/<int:instrument_id>/<int:chart_id>/<int:list_id>', views.m_delete_instrument, name="m_delete_instrument"),
    path('selectModifyMode/<int:list_id>/<int:chart_id>', views.select_modify_mode, name="select_modify_mode"),
    path('getDeleteList/<int:chart_id>', views.get_delete_list, name="get_delete_list"),
    path('DeleteList/<int:list_id>/<int:chart_id>', views.delete_list, name="delete_list"),
    path('writeJson', views.write_json, name="write_json"),
    path('update_chart_settings', views.update_chart_settings),
    path('update_overlay', views.update_overlay),
    path('update_indicator', views.update_indicator),
    path('delete_overlay/<int:chart_id>/<int:overlay_id>', views.delete_overlay),
    path('delete_indicator/<int:chart_id>/<int:indicator_id>', views.delete_indicator)
]

optimize/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, date
# Create your models here.

class PeriodTree(models.Model):
    child_id = models.IntegerField(default=0)
    child_name = models.CharField(max_length=100)
    child_type = models.IntegerField(default=0)
    parent_id = models.IntegerField(default=0)
    permission = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class PeriodFolder(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    path = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Result(models.Model):
    Total_return = models.DecimalField(max_digits=6, decimal_places=2,default=0.0)
    Benchmark_return = models.DecimalField(max_digits=6, decimal_places=2,default=0.0)
    Annualized_return = models.DecimalField(max_digits=6, decimal_places=2,default=0.0)
    Max_drawdown = models.DecimalField(max_digits=6, decimal_places=2,default=0.0)
    Benchmark_max_drawdown = models.DecimalField(max_digits=6, decimal_places=2,default=0.0)
    pctwinners = models.DecimalField(max_digits=6, decimal_places=2,default=0.0)
    Sharpe_ratio = models.DecimalField(max_digits=6, decimal_places=2,default=0.0)
    date = models.DateField(auto_now_add=True)        

class PeriodStrategy(models.Model): 
    name = models.CharField(max_length=100)
    offset_choice = (
        ('day', 'day'),
        ('week', 'week'),
        ('month', 'month'),
    )
    period_choice = (
        ('6 months', '6 months'),
        ('1 year', '1 year'),
        ('2 year', '2 year'),
    )
    offset = models.CharField("Offset", max_length=20, null=True, blank=True, choices=offset_choice)
    period = models.CharField("Period", max_length=20, null=True, blank=True, choices=period_choice)    
    startdate = models.DateField("StartDate", default=datetime.strptime('1999-01-01', "%Y-%m-%d").date())
    enddate = models.DateField("EndDate", default=datetime.strptime('2018-12-31', "%Y-%m-%d").date())    
    strategy = models.OneToOneField('backtest.Strategy', related_name='period_strategy', null=True, blank=True, on_delete=models.SET_NULL)
    results = models.OneToOneField(Result, on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name    

backtest/templates/backtest/comb_strategy/add_strategy.html
{% extends 'backtest/comb_strategy/comb_strategy_base.html' %}

{% block content %}
<div class="table-container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-4">
            <form action="{% url 'backtest:comb_add_strategy' id_comb_strategy=id_comb_strategy %}" method="post">
                {% csrf_token %}
                <h2 class="strategy_title text-left">Strategy List</h2>
                <table class="table">
                    <tbody>
                        {% for strategy in strategies %}
                        <tr>
                            <td>{{strategy}}</td>
                            <td><input type="checkbox" class="form-control" name="strategy[]" value="{{strategy.id}}">
                            </td>
                        </tr>
                        {% empty %}
                        <tr><td>No Strategies</td></tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a class="btn btn-primary pull-right" style="margin-top: 30px" href="{% url 'backtest:comb_manage_strategy' id_strategy=id_comb_strategy %}">Back to my strategy</a>
                <input type="submit" value="Add" class="btn btn-primary pull-right" style="margin-top: 30px; margin-right: 4px;" />
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
{% endblock %}

backtest/templates/backtest/comb_strategy/comb_strategy_base.html
{% extends "backtest/backtest_base.html" %}

{% load static %}

{% block sidebar %}
<div class="navbar-button">
    <a href="{% url 'backtest:comb_create_folder' %}"><img src="{% static 'img/add.png' %}" width="30px"
            height="30px" /></a>
    <a href="{% url 'backtest:comb_delete_folder' %}"><img src="{% static 'img/delete.png' %}" width="30px"
            height="30px"></a>
</div>
<ul class="nav flex-column pl-1">
    <li class="nav-item">
        <h5><a href="{% url 'backtest:comb_manage_strategies' id_folder=0 %}">Strategy List</a></h5>
    </li>
    <div id="jstree-tree" class="well col-sm-3"></div>
</ul>
{% endblock %}

{% block mainnav %}
<nav class="navbar navbar-fixed-top navbar-toggleable-sm navbar-inverse bg-primary mb-3 customnavbacktest">
    <ul class="navbar-nav">
        <li class="nav-item text-center">
            <a class="nav-link customlinkbacktest menu_custom" href="{% url 'backtest:comb_strategy' %}">Strategy</a>
        </li>
        <li class="nav-item text-center">
            <a class="nav-link customlinkbacktest menu_custom" href="{% url 'backtest:comb_results' %}">Results</a>
        </li>
    </ul>
</nav>
{% endblock %}
{% block subjs %}
<script>
    $(document).ready(function () {
        toastr.options = {
            'closeButton': true,
            'debug': false,
            'newestOnTop': false,
            'progressBar': true,
            'positionClass': 'toast-top-right',
            'preventDuplicates': false,
            'showDuration': '1000',
            'hideDuration': '1000',
            'timeOut': '5000',
            'extendedTimeOut': '1000',
            'showEasing': 'swing',
            'hideEasing': 'linear',
            'showMethod': 'fadeIn',
            'hideMethod': 'fadeOut',
        }
    })
    var tree_structure = "{{tree_structure|safe}}";
    if (tree_structure) {
        tree_structure = tree_structure.replace(/'/g, '"');
        tree_structure = JSON.parse(tree_structure)
        $('#jstree-tree')
            .on('select_node.jstree', function (e, data) {
                var objNode = data.instance.get_node(data.selected);
                if (objNode) {
                    $.ajax({
                        method: "GET",
                        url: "{% url 'backtest:comb_get_tree_element' %}",
                        data: {
                            "id": objNode.id
                        },
                        success: function (data) {
                            if (data.child_type == 1 && data.permission == 0) {
                                var url = "{% url 'backtest:comb_manage_strategies' id_folder=123 %}";
                                location.href = url.replace('123', data.child_id);
                            }
                            if(data.child_type == 1 && data.permission == 1){
                                location.href = "{% url 'backtest:comb_manage_strategies' id_folder=99999999999 %}";
                            }
                            if (data.child_type == 2) {
                                var url = "{% url 'backtest:comb_manage_strategy' id_strategy=123 %}";
                                location.href = url.replace('123', data.child_id);
                            }
                        }
                    })
                }
            })
            .jstree({
                core: {
                    data: tree_structure
                }
            });
    }
    var error_message = "{{error_message|safe}}"
    if (error_message) {
        toastr.error(error_message)
    }

</script>
{% endblock %}

backtest/templates/backtest/comb_strategy/create_combination_strategy.html
{% extends 'backtest/comb_strategy/comb_strategy_base.html' %}

{% load static %}

{% block content %}
<div class="table-container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-4">
            <form action="{% url 'backtest:comb_create_comb_strategy' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <label>Parent Folder:</label>
                <select class="form-control" name="parent_id" required>
                    <option value="0">Top level</option>
                    {% for folder in folders %}
                    <option value="{{ folder.id }}">{{folder.path}}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="Add" class="btn btn-primary pull-right" style="margin-top: 30px" />
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
<script>

</script>
{% endblock content %}

backtest/templates/backtest/comb_strategy/create_folder.html
{% extends 'backtest/comb_strategy/comb_strategy_base.html' %}

{% load static %}

{% block content %}
<div class="table-container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-4">
            <form action="#" method="post">
                {% csrf_token %}
                <h2 class="strategy_title text-left">Create Folder</h2>
                <label>Name:</label>
                <input type="text" name="folder_name" class="form-control" required>
                <label>Parent Folder:</label>
                <select class="form-control" name="parent_id" required>
                    <option value="0">Top level</option>
                    {% for folder in folders %}
                    <option value="{{ folder.id }}">{{folder.path}}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="Create" class="btn btn-primary pull-right" style="margin-top: 30px" />
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
<script>
</script>
{% endblock content %}

backtest/templates/backtest/comb_strategy/delete_folder.html
{% extends 'backtest/comb_strategy/comb_strategy_base.html' %}

{% load static %}

{% block content %}
<div class="table-container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-4">
            <form action="{% url 'backtest:comb_delete_folder' %}" method="post">
                {% csrf_token %}
                <h2 class="strategy_title text-left">Delete Folder</h2>
                <label>Select folder you are going to delete :</label>
                <select class="form-control" name="id" required>
                    {% for folder in folders %}
                    <option value="{{ folder.id }}">{{folder.path}}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="Delete" class="btn btn-primary pull-right" style="margin-top: 30px" />
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
<script>

</script>
{% endblock content %}

backtest/templates/backtest/comb_strategy/delete_strategy.html
{% extends 'backtest/comb_strategy/comb_strategy_base.html' %}

{% load static %}

{% block content %}
<div class="table-container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-4">
            <form action="{% url 'backtest:comb_delete_strategy' id_strategy=comb_strategy.id %}" method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete this combination strategy "{{ comb_strategy.name }}"?</p>
                {{ form.as_p }}
                <input type="submit" value="Confirm" class="btn btn-primary pull-right" style="margin-top: 30px" />
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
<script>

</script>
{% endblock content %}

backtest/templates/backtest/comb_strategy/load_file_list.html
{% extends "backtest/strategies/strategy_base.html" %}

{% load static %}

{% block content %}
<div class="table-container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-4">
            <form action="{% url 'backtest:comb_load_strategy' %}" method="post">
                {% csrf_token %}
                <h2 class="strategy_title text-left">Combination Strategy Load List</h2>
                <label>File List:</label>
                <select class="form-control" name="file_name" required>
                    {% for file in load_list %}
                    <option value="{{ file  }}">{{ file }}</option>
                    {% endfor %}
                </select>
                <label>Parent Folder:</label>
                <select class="form-control" name="parent_id" required>
                    {% if user.is_superuser %}
                    <option value="d">Default folder</option>
                    {% endif %}
                    <option value="0">Top level</option>
                    {% for folder in folders %}
                    <option value="{{ folder.id }}">{{folder.path}}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="Load" class="btn btn-primary pull-right" style="margin-top: 30px" />
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
<script>

</script>
{% endblock content %}

backtest/templates/backtest/comb_strategy/manage_strategies.html
{% extends 'backtest/comb_strategy/comb_strategy_base.html' %}

{% load static %}

{% block content %}
<div class="table-container">
    <div class="displayoposite">
        <h4 class="strategy_title">{{title}}</h4>
    </div>
    <div class="flex-wrap">
        <a href="{% url 'backtest:comb_create_comb_strategy' %}" class="btn btn-primary">Create Combination Strategy</a>
        <a href="{% url 'backtest:comb_load_strategy' %}" class="btn btn-primary">Load Combination Strategy</a>
    </div>
    <table class="table sortable" style="margin-top: 10px;">
        <thead>
            <tr>
                <th>Combination Strategies</th>
                <th>Export</th>
                <th>Delete</th>
            </tr>            
        </thead>
        <tbody>
            {% for comb_strategy in comb_strategies %}
                <tr>
                    <td><a href="{% url 'backtest:comb_manage_strategy' id_strategy=comb_strategy.id %}">{{comb_strategy}}</a></td>
                    <td><a href="{% url 'backtest:comb_export_strategy' id_folder=id_folder id_strategy=comb_strategy.id %}">Export</a></td>
                    <td><a href="{% url 'backtest:comb_delete_strategy' id_strategy=comb_strategy.id %}"><i class="fa fa-trash"
                        aria-hidden="true"></i>Delete</a></td>
                </tr>
            {% empty %}
                <tr><td>No Combination Strategies</td></tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

backtest/templates/backtest/comb_strategy/modify_general.html
{% extends 'backtest/comb_strategy/comb_strategy_base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="table-container">
    <div class="row" style="margin-bottom: 40px">
        <div class="col-md-3 col-sm-3 col-3"></div>
        <div class="col-md-4 col-sm-4 col-4">
            <form action="{% url 'backtest:comb_modify_general' id_comb_strategy=id_comb_strategy %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" id="submit" class="btn btn-primary pull-right" value="Modify" disabled >
            </form>
        </div>
        <div class="col-md-4 col-sm-4 col-4"></div>
    </div>
</div>
<script>
    function date_validate(){
        var start_date = $("#id_startdate").val();
        var end_date = $("#id_enddate").val()
        if (new Date(start_date) < new Date("1999-01-01") || new Date(end_date) < new Date("1999-01-01")) {
            toastr.error("Date can't be ealier than January 1, 1999");
            $("#submit").prop('disabled', true);
        }
        else if (new Date(start_date) > new Date() || new Date(end_date) > new Date()) {
            toastr.error("Date can't be late than Today");
            $("#submit").prop('disabled', true);
        }
        else {
            $("#submit").prop('disabled', false);
        }
    }
    $("#id_startdate").on('dp.change', function (e) {
        date_validate()
    });
    $("#id_enddate").on('dp.change', function (e) {
        date_validate()
    });
</script>
{% endblock content %}