InteractiveAlpha/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('', include('backtest.urls')),
    path('chart/', include('chart.urls')),
    path('tools/', include('tools.urls')),
    path('optimize/', include('optimize.urls')),
]

chart/urls.py
from django.urls import path
from . import views
app_name = 'chart'
urlpatterns = [
    path('', views.view_chart, name="view_chart"),
    path('addChart', views.add_chart, name="add_chart"),
    path('removeChartList', views.remove_chart_list, name="remove_chart_list"),
    path('removeChart/<int:chart_id>', views.remove_chart, name="remove_chart"),
    path('addList/<int:chart_id>', views.add_list, name="add_list"),
    path('addList/<int:chart_id>/<int:list_id>/<str:f_name>', views.add_universe, name="add_universe"),
    path('addInstrument/<int:chart_id>/<int:list_id>/<str:f_name>', views.add_instrument, name="add_instrument"),
    path('getInstrument/', views.get_instrument, name="get_instrument"),
    path('viewInstrument/', views.view_instrument, name="view_instrument"),
    path('getModifyList/<int:chart_id>', views.get_modify_list, name="get_modify_list"),
    path('modifyChangeName/<int:list_id>/<int:chart_id>', views.modify_change_name, name="m_change_name"),
    path('modifyAddInstrument/<int:list_id>/<int:chart_id>', views.modify_add_instrument, name="m_add_instrument"),
    path('getDeleteInstruments/<int:list_id>/<int:chart_id>', views.get_delete_instruments, name="get_delete_instruments"),
    path('modifyDeleteInstruments/<int:instrument_id>/<int:chart_id>/<int:list_id>', views.m_delete_instrument, name="m_delete_instrument"),
    path('selectModifyMode/<int:list_id>/<int:chart_id>', views.select_modify_mode, name="select_modify_mode"),
    path('getDeleteList/<int:chart_id>', views.get_delete_list, name="get_delete_list"),
    path('DeleteList/<int:list_id>/<int:chart_id>', views.delete_list, name="delete_list"),
    path('writeJson', views.write_json, name="write_json"),
    path('update_chart_settings', views.update_chart_settings),
    path('update_overlay', views.update_overlay),
    path('update_indicator', views.update_indicator),
    path('delete_overlay/<int:chart_id>/<int:overlay_id>', views.delete_overlay),
    path('delete_indicator/<int:chart_id>/<int:indicator_id>', views.delete_indicator)
]

tools/urls.py
from django.urls import path
from . import views

app_name = 'tools'

urlpatterns = [

    path('', views.Index, name="index"),

    #UNIVERSES url
    path('universes/', views.ManageUniverses_default, name="manage_universes_default"),
    path('universes/create_folder/', views.CreateFolder, name="create_folder"),
    path('universes/delete_folder/', views.DeleteFolder, name="delete_folder"),
    path('universes/<int:id>', views.ManageUniverses, name="manage_universes"),

    path('universes/universe/', views.ManageUniverse_default, name="manage_universe_default"),
    path('universes/upload_universe/', views.UploadUniverse, name="upload_universe"),
    path('universe/delete_universe_default/', views.DeleteUniverse_default, name="delete_universe_default"),
    path('universe/add_instrument_default/<int:id>', views.AddInstrument_default, name="add_instrument_default"),
    path('universe/add_instrument_to_universe', views.AddInstrumenttoUniverse, name="add_instrument_to_universe"),
    path('universe/delete_instrument_default/<int:id>', views.DeleteInstrument_default, name="delete_instrument_default"),

    path('universes/create_universe/', views.CreateUniverse, name="create_universe"),
    path('universes/delete_universe/', views.DeleteUniverse, name="delete_universe"),
    path('universes/universe/<int:id>', views.ManageUniverse, name="manage_universe"),
    path('universes/universe/default/<int:id>', views.ManageDefaultUniverse, name="manage_default_universe"),

    path('universes/universe/add_instrument/<int:id>', views.AddInstrument, name="add_instrument"),
    # path('universes/universe/insert_instrument/', views.InsertInstrument, name="insert_instrument"),
    # path('universes/universe/update_instrument/', views.UpdateInstrument, name="update_instrument"),
    path('universes/universe/delete_instrument/', views.DeleteInstrument, name="delete_instrument"),

    path('universes/boolean_operation/', views.BooleanOperation, name="manage_boolean_operation"),

    path('universe/ajax_get_treeelement/', views.ajax_get_treeelement, name='ajax_get_treeelement'),
    path('universe/get_instrument_of_universe', views.ajax_get_instrument_of_universe, name="get_instrument_of_universe"), 


    #LISTS url
    path('lists/', views.LManageUniverses_default, name="lists_manage_universes_default"),
    path('lists/create_folder/', views.LCreateFolder, name="lists_create_folder"),
    path('lists/delete_folder/', views.LDeleteFolder, name="lists_delete_folder"),
    path('lists/<int:id>', views.LManageUniverses, name="lists_manage_universes"),

    path('lists/list/', views.LManageUniverse_default, name="lists_manage_universe_default"),
    path('lists/upload_universe/', views.LUploadUniverse, name="lists_upload_universe"),
    path('list/delete_universe_default/', views.LDeleteUniverse_default, name="lists_delete_universe_default"),
    path('list/add_instrument_default/<int:id>', views.LAddInstrument_default, name="lists_add_instrument_default"),
    path('list/add_instrument_to_universe', views.LAddInstrumenttoUniverse, name="lists_add_instrument_to_universe"),
    path('list/delete_instrument_default/<int:id>', views.LDeleteInstrument_default, name="lists_delete_instrument_default"),

    path('lists/create_universe/', views.LCreateUniverse, name="lists_create_universe"),
    path('lists/delete_universe/', views.LDeleteUniverse, name="lists_delete_universe"),
    path('lists/list/<int:id>', views.LManageUniverse, name="lists_manage_universe"),
    path('lists/list/default/<int:id>', views.LManageDefaultUniverse, name="lists_manage_default_universe"),

    path('lists/list/add_instrument/<int:id>', views.LAddInstrument, name="lists_add_instrument"),
    # path('universes/universe/insert_instrument/', views.InsertInstrument, name="lists_insert_instrument"),
    # path('universes/universe/update_instrument/', views.UpdateInstrument, name="lists_update_instrument"),
    path('lists/list/delete_instrument/', views.LDeleteInstrument, name="lists_delete_instrument"),

    path('lists/boolean_operation/', views.LBooleanOperation, name="lists_manage_boolean_operation"),

    path('list/ajax_get_treeelement/', views.Lajax_get_treeelement, name='lists_ajax_get_treeelement'),
    path('list/get_instrument_of_universe', views.Lajax_get_instrument_of_universe, name="lists_get_instrument_of_universe"),

    #BENCHMARKS url
    path('benchmarks/', views.BManageUniverses_default, name="benchmarks_manage_universes_default"),
    path('benchmarks/create_folder/', views.BCreateFolder, name="benchmarks_create_folder"),
    path('benchmarks/delete_folder/', views.BDeleteFolder, name="benchmarks_delete_folder"),
    path('benchmarks/<int:id>', views.BManageUniverses, name="benchmarks_manage_universes"),

    path('benchmarks/benchmark/', views.BManageUniverse_default, name="benchmarks_manage_universe_default"),
    path('benchmarks/upload_universe/', views.BUploadUniverse, name="benchmarks_upload_universe"),
    path('benchmark/delete_universe_default/', views.BDeleteUniverse_default, name="benchmarks_delete_universe_default"),
    path('benchmark/add_instrument_default/<int:id>', views.BAddInstrument_default, name="benchmarks_add_instrument_default"),
    path('benchmark/add_instrument_to_universe', views.BAddInstrumenttoUniverse, name="benchmarks_add_instrument_to_universe"),
    path('benchmark/delete_instrument_default/<int:id>', views.BDeleteInstrument_default, name="benchmarks_delete_instrument_default"),

    path('benchmarks/create_universe/', views.BCreateUniverse, name="benchmarks_create_universe"),
    path('benchmarks/delete_universe/', views.BDeleteUniverse, name="benchmarks_delete_universe"),
    path('benchmarks/benchmark/<int:id>', views.BManageUniverse, name="benchmarks_manage_universe"),
    path('benchmarks/benchmark/default/<int:id>', views.BManageDefaultUniverse, name="benchmarks_manage_default_universe"),

    path('benchmarks/benchmark/add_instrument/<int:id>', views.BAddInstrument, name="benchmarks_add_instrument"),
    # path('universes/universe/insert_instrument/', views.InsertInstrument, name="benchmarks_insert_instrument"),
    # path('universes/universe/update_instrument/', views.UpdateInstrument, name="benchmarks_update_instrument"),
    path('benchmarks/benchmark/delete_instrument/', views.BDeleteInstrument, name="benchmarks_delete_instrument"),

    path('benchmark/ajax_get_treeelement/', views.Bajax_get_treeelement, name='benchmarks_ajax_get_treeelement'),
    path('benchmark/get_instrument_of_universe', views.Bajax_get_instrument_of_universe, name="benchmarks_get_instrument_of_universe"),

    #RANKING URL
    path('ranksystems/', views.RManageRankSystems, name="rank_manage_rank_systems"),
    path('ranksystems/<int:parent_id>', views.RManageRankSystems_folder, name="rank_manage_rank_systems_folder"),
    path('ranksystems/add_ranking_system/', views.RAddRankSystem, name="rank_add_ranking_system"),
    path('ranksystems/delete_ranking_system/<int:id>',views.RDeleteRankingSystem, name="rank_delete_ranking_system"),
    path('ranksystems/export/<int:id_rank_system>/<int:id_parent>', views.RExportRankingSystem, name="rank_export_ranking_system"),
    path('ranksystems/load_ranking_system/', views.RLoadRankingSystem, name="rank_load_ranking_system"),
    path('ranksystems/manage_ranking_system/<int:id>',views.RManageRankingSystem, name="rank_manage_ranking_system"),
    path('ranksystems/manage_rank_get_data/', views.RGetRankData, name="rank_get_data"),

    path('ranksystems/add_ranking_rule/<int:id>',views.RAddRankingRule, name="rank_add_ranking_rule"),
    path('ranksystems/modify_ranking_rule/<int:id_rank>/<int:id_rule>', views.RModifyRule, name="rank_modify_rule"),
    path('ranksystem/get_indicator/<int:id_rule>/<int:id_rank>', views.ajax_get_tech, name='rank_get_tech'),
    path('ranksystem/delete_rule/', views.RDeleteRule, name="rank_delete_rule"),

    path('ranksystems/add_indicator/<str:source>/<slug:indicator>$/add/<int:id_rank>', views.RAddIndicator, name='rank_add_indicator'),
    path('ranksystems/rank_get_indicator/<int:id_rank>', views.RGetIndicator, name="rank_get_indicator"),
    path('ranksystems/rank_get_indicator_add', views.RGetIndicatorAdd, name="rank_get_indicator_add"),
    path('ranksystems/modifytechnical/<str:indicator>/<int:tech_id>/<int:id_rank>/<str:requestfrom>/<int:requestrule>', views.RModifyIndicator, name='rank_modifytechnical'),
    path('ranksystems/deletetechnical/<int:tech_id>/<int:id_rank>/<str:requestfrom>/<int:requestrule>', views.RDeleteIndicator, name='rank_deletetechnical'),

    path('ranksystems/add_indicator_combination/<int:id>', views.RAddIndicatorCombination, name="rank_add_indicator_combination"),
    path('ranksystems/modify_indicator_combination/<int:id_comb>/<int:id_system>', views.RModifyIndicatorCombination, name="rank_modify_combination"),
    path('ranksystems/get_techs_comb/<int:id_comb>', views.RGetTechs, name="rank_get_techs_comb"),
    path('ranksystems/get_indicator_basic/<int:id_system>', views.RGetIndicatorBasic, name="rank_get_indicators_basic"),

    path('ranksystems/createfolder/', views.RCreateFolder, name="rank_create_folder"),
    path('ranksystems/deletefolder/', views.RDeleteFolder, name='rank_delete_folder'),

    path('ranksystems/default/', views.RManageDefaultSystems, name="rank_manage_default_systems"),

    #LIQUIDITY URL
    path('liquiditysystems/', views.LSManageLiquiditySystems, name="liqudity_manage_liquidity_systems"),
    path('liquiditysystems/<int:parent_id>', views.LSManageLiquiditySystems_folder, name="liquidity_manage_liquidity_system_folder"),
    path('liquiditysystems/add_liquidity_system/', views.LSAddLiquiditySystem, name="liquidity_add_liquidity_system"),
    path('liquiditysystems/export/<int:id_system>/<int:id_parent>', views.LSExportLiquiditySystem, name="liquidity_export_liquidity_system"),

tools/forms.py
from django import forms

from .models import Universe_Default, Lists_Default, Benchmarks_Default, Ranking_System, Ranking_Rule, Liquidity_System, Liquidity_Rule
                    # Indicators_Combination, Indicators_Combination_System

class UniverseForm(forms.ModelForm):
    class Meta:
        model = Universe_Default
        fields = ('file',)

class ListForm(forms.ModelForm):
    class Meta:
        model = Lists_Default
        fields = ('file',)

class BenchmarkForm(forms.ModelForm):
    class Meta:
        model = Benchmarks_Default
        fields = ('file',)

class RankingSystemForm(forms.ModelForm):
    class Meta:
        model = Ranking_System
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }
        def clean(self):
            cleaned_data = super(RankingSystemForm, self).clean()           
            return cleaned_data 

class RankingRuleForm(forms.ModelForm):
    class Meta:
        model = Ranking_Rule
        fields = '__all__'
        exclude = ('rank_id',)
        widgets = {
            'weight': forms.NumberInput(attrs={'class':'form-control'}),
            'indicator': forms.TextInput(attrs={'class':'form-control','id':'indicator'}),
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'direction': forms.Select(attrs={'class':'form-control'}),
        }
        def clean(self):
            cleaned_data = super(RankingRuleForm, self).clean()           
            return cleaned_data 

#LIQUIDITY SYSTEM
class LiquiditySystemForm(forms.ModelForm):
    class Meta:
        model = Liquidity_System
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }
        def clean(self):
            cleaned_data = super(LiquiditySystemForm, self).clean()           
            return cleaned_data 

class LiquidityRuleForm(forms.ModelForm):
    class Meta:
        model = Liquidity_Rule
        fields = '__all__'
        widgets = {
            'min_amount': forms.NumberInput(attrs={'class':'form-control'}),
            'max_amount': forms.NumberInput(attrs={'class':'form-control'}),
            'rule': forms.TextInput(attrs={'class':'form-control', 'id':'liquidity_rule'}),
            'name': forms.TextInput(attrs={'class':'form-control'}),
        }
        def clean(self):
            cleaned_data = super(LiquidityRuleForm, self).clean()           
            return cleaned_data 

tools/templates/tools/ranking_system/add_ranking_rule.html
{% extends "tools/base_tools.html" %}

{% load static %}

{% block sidebar %}
<ul class="nav flex-column pl-1">
    <div id="jstree-tree" class="well col-sm-3"></div>
</ul>
{% endblock %}

{% block content %}
<div class="table-container">
    <div class="row">
        <div class="col-md-6">
            <form action="{% url 'tools:rank_add_ranking_rule' id=rank_system_id %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-group" style="margin-top: 30px;">
                    <input type="submit" value="Add this rule" class="btn btn-primary" />
                    <a class="btn btn-primary"
                        href="{% url 'tools:rank_manage_ranking_system' id=rank_system_id %}">Back to my
                        ranking system</a>
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <p>Indicators Available:</p>
            <input class="form-control technical"></input>
        </div>
    </div>
</div>
<div id="modal-div"></div>
<script>
    var token = '{{csrf_token}}';
    var rank_id = "{{rank_system_id}}";
    var modalDiv = $("#modal-div");
    var flag = false;
    $(document).ready(function () {
        $.ajax({
            method: "GET",
            url: '{% url "tools:rank_get_indicator" id_rank=rank_system_id %}',
            dataType: "html",
            async: false,
            success: function (data) {
                var rules = data.split(',');
                $('.technical').tagEditor({
                    initialTags: rules,
                    beforeTagDelete: function (field, editor, tags, val) {
                        $.ajax({
                            headers: { "X-CSRFToken": token },
                            method: "GET",
                            url: '{% url "tools:rank_get_indicator_add" %}',
                            data: {
                                'techindicator': val,
                                'id_rank': rank_id,
                                'from': 'add',
                            },
                            success: function (data) {
                                modalDiv.html(data);
                                $("#myEdit").modal('show');
                            }
                        })
                        return flag;
                    },
                });
                $('#indicator').tagEditor({ initialTags: [] });
            }
        });
    });
    var indicator_tree = "{{indicator_tree|safe}}";
    if (indicator_tree) {
        indicator_tree = indicator_tree.replace(/'/g, '"');
        indicator_tree = JSON.parse(indicator_tree)
        var action_url = "{% url 'tools:rank_add_indicator' source='add' indicator='000000' id_rank=rank_system_id %}";
        $('#jstree-tree')
            .on('select_node.jstree', function (e, data) {
                var objNode = data.instance.get_node(data.selected)
                if (objNode.parent != "#") {
                    $.ajax({
                        url: action_url.replace('000000', objNode.text),
                        success: function (data) {
                            modalDiv.html(data);
                            $("#myEdit").modal('show');
                        }
                    })
                }
            })
            .jstree({
                core: {
                    data: indicator_tree
                }
            });
    }
</script>
{% endblock content %}

tools/templates/tools/ranking_system/base_ranking_system.html
{% extends "tools/base_tools.html" %}

{% load static %}

{% block sidebar %}
<ul class="nav flex-column pl-1">
    <div class="navbar-button">
        <a href="{% url 'tools:rank_create_folder' %}"><img src="{% static 'img/add.png' %}" width="30px" height="30px"
                title="Create Folder" /></a>
        <a href="{% url 'tools:rank_delete_folder' %}"><img src="{% static 'img/delete.png' %}" width="30px"
                height="30px" title="Delete Folder"></a>
    </div>
    <li class="nav-item">
        <h5><a href="{% url 'tools:rank_manage_rank_systems_folder' parent_id=0 %}">Ranking System Structure</a></h5>
    </li>
    <div id="jstree-tree" class="well col-sm-3"></div>
</ul>
{% endblock %}

{% block subjs %}
<script>
    var tree_structure = "{{tree_structure|safe}}";
    if (tree_structure) {
        tree_structure = tree_structure.replace(/'/g, '"');
        tree_structure = JSON.parse(tree_structure)
        $('#jstree-tree')
            .on('select_node.jstree', function (e, data) {
                var objNode = data.instance.get_node(data.selected);
                if (objNode) {
                    $.ajax({
                        method: "GET",
                        url: "{% url 'tools:rank_get_data' %}",
                        data: {
                            "id": objNode.id
                        },
                        success: function (data) {
                            if (data.child_type == 2 ) {
                                var url = "{% url 'tools:rank_manage_ranking_system' id=123 %}"
                                location.href = url.replace('123', data.child_id)
                            }
                            if (data.child_type == 1 && data.permission == 0) {
                                var url = "{% url 'tools:rank_manage_rank_systems_folder' parent_id=123 %}"
                                location.href = url.replace('123', data.child_id)
                            }
                            if (data.child_type == 1 && data.permission == 1) {
                                location.href = "{% url 'tools:rank_manage_default_systems' %}"
                            }
                        }
                    })
                }
            })
            .jstree({
                core: {
                    data: tree_structure
                }
            });
    }
</script>
{% endblock %}

tools/templates/tools/ranking_system/manage_default_systems.html
{% extends "tools/ranking_system/base_ranking_system.html" %}

{% load static %}

{% block content %}
<div class="table-container">
    <div class="displayoposite">
        <h4 class="strategy_title">{{folder}}</h4>
    </div>
    <div class="btn-group flex-wrap" role="group">
        <a href="{% url 'tools:rank_add_ranking_system' %}" class="btn btn-primary margin-right-5"> Add Ranking System
        </a>
        <a href="{% url 'tools:rank_load_ranking_system' %}" class="btn btn-primary margin-right-5"> Load Ranking System
        </a>
    </div>
    <table class="table sortable" style="margin-top:10px">
        <tr>
            <th>Name</th>
            <th>Export</th>
            {% if user.is_superuser %}
            <th>Delete</th>
            {% endif %}
        </tr>
        {% for ranking_system in ranking_systems %}
        <tr>
            <td><a href="{% url 'tools:rank_manage_ranking_system' id=ranking_system.id %}">{{ranking_system}}</a></td>
            <td><a href="{% url 'tools:rank_export_ranking_system' id_rank_system=ranking_system.id id_parent=999999999999 %}">Export</a></td>
            {% if user.is_superuser %}
            <td><a href="{% url 'tools:rank_delete_ranking_system' id=ranking_system.id %}"><i class="fa fa-trash"
                        aria-hidden="true"></i> Delete </a></td>
            {% endif %}
            {% empty %}
            <td>No Ranking System!</td>
        </tr>
        {% endfor %}
    </table>
</div>
<script>
    error_message = "{{error_message}}"
    $(document).ready(function () {
        if (error_message) {
            toastr.error('Not Empty Folder')
        }
    })
</script>
{% endblock %}

tools/templates/tools/ranking_system/manage_ranking_system.html
{% extends "tools/ranking_system/base_ranking_system.html" %}

{% load static %}

{% block content %}
<div class="table-container">
    <div class="displayoposite">
        <h4 class="strategy_title">{{relative_path}}{{ranking_system}}</h4>
    </div>
    {% if not user.is_superuser and relative_path == 'Default Folder/' %}
    {% else %}
    <div class="flex-wrap">
        <a href="{% url 'tools:rank_add_indicator_combination' id=ranking_system.id %}" class="btn btn-primary">Add
            Indicator Combination
        </a>
        <a href="{% url 'tools:rank_add_ranking_rule' id=ranking_system.id %}" class="btn btn-primary">Add Ranking Rule
        </a>
    </div>
    {% endif %}
    <div class="row" style="margin-top: 10px;">
        <div class="col-md-12">
            <div class="tab">
                <button class="tablinks active" style="width: 50%;" onclick="openCity(event, 'Combinations')">Indicator
                    Combinations</button>
                <button class="tablinks" style="width: 50%;" onclick="openCity(event, 'Rules')">Rules</button>
            </div>
        </div>
    </div>
    <div id="Combinations" class="tabcontent active">
        <table class="table">
            <thead>
                <th>Indicator Combinations:</th>
                {% if not user.is_superuser and relative_path == 'Default Folder/' %}
                {% else %}
                <th>Delete:</th>
                {% endif %}
            </thead>
            <tbody>
                {% for combination in indicator_combinations %}
                <tr>
                    {% if not user.is_superuser and relative_path == 'Default Folder/' %}
                    <td>{{combination}}
                    </td>
                    {% else %}
                    <td><a
                            href="{% url 'tools:rank_modify_combination' id_comb=combination.id id_system=ranking_system.id %}">{{combination}}</a>
                    </td>
                    <td><a href="#" class="confirm-delete" data-toggle="modal" data-target="#myModal"
                            data-type="combination" data-rule="{{combination.id}}" data-rank="{{ranking_system.id}}">
                            <i class="fa fa-trash" aria-hidden="true"></i>Delete </a> </td>
                    {% endif %}
                </tr>
                {% empty %}
                <tr>
                    <td colspan="2">No Indicator Combination</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div id="Rules" class="tabcontent">
        <table class="table sortable">
            <tr>
                <th>Weight:</th>
                <th>Indicators</th>
                <th>Name:</th>
                <th>Direction:</th>
                {% if not user.is_superuser and relative_path == 'Default Folder/' %}
                {% else %}
                <th>Delete:</th>
                {% endif %}
            </tr>
            {% if not user.is_superuser and relative_path == 'Default Folder/' %}
            {% for ranking_rule in ranking_rules %}
            <tr>
                <td><a>{{ranking_rule.weight}}</a>
                </td>
                <td><a>{{ranking_rule.indicator}}</a>
                </td>
                <td><a>{{ranking_rule.name}}</a>
                </td>
                {% if ranking_rule.direction == "HB" %}
                <td><a>Higher is better</a></td>
                {% elif ranking_rule.direction == "LB" %}
                <td><a>Lower is better</a></td>
                {% endif %}
                {% empty %}
                <td>No Ranking Rules!</td>
            </tr>
            {% endfor %}
            {% else %}
            {% for ranking_rule in ranking_rules %}
            <tr>
                <td><a
                        href="{% url 'tools:rank_modify_rule' id_rank=ranking_system.id id_rule=ranking_rule.id %}">{{ranking_rule.weight}}</a>
                </td>
                <td><a
                        href="{% url 'tools:rank_modify_rule' id_rank=ranking_system.id id_rule=ranking_rule.id %}">{{ranking_rule.indicator}}</a>
                </td>
                <td><a
                        href="{% url 'tools:rank_modify_rule' id_rank=ranking_system.id id_rule=ranking_rule.id %}">{{ranking_rule.name}}</a>
                </td>
                {% if ranking_rule.direction == "HB" %}
                <td><a href="{% url 'tools:rank_modify_rule' id_rank=ranking_system.id id_rule=ranking_rule.id %}">Higher
                        is
                        better</a></td>
                {% elif ranking_rule.direction == "LB" %}
                <td><a href="{% url 'tools:rank_modify_rule' id_rank=ranking_system.id id_rule=ranking_rule.id %}">Lower
                        is
                        better</a></td>
                {% endif %}
                <td><a href="#" class="confirm-delete" data-toggle="modal" data-target="#myModal" data-type="rule"
                        data-rule="{{ranking_rule.id}}" data-rank="{{ranking_system.id}}">
                        <i class="fa fa-trash" aria-hidden="true"></i>Delete </a> </td>
                {% empty %}
                <td>No Ranking Rules!</td>
            </tr>
            {% endfor %}
            {% endif %}
            </tr>
        </table>
    </div>
</div>
<div id="myModal" class="modal fade" role="dialog">
    <form method="post" action="{% url 'tools:rank_delete_rule' %}">
        {% csrf_token %}
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-body">
                    <h5 class="modal-title">Are you sure you want to delete?</h5>
                    <input type="hidden" name="rank_id" id="rank_id" />
                    <input type="hidden" name="id" id="deleteid" />
                    <input type="hidden" name="type" id="type" />
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Delete</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    $(document).ready(function () {
        $(document).on("click", ".confirm-delete", function () {
            $("#deleteid").val($(this).data('rule'))
            $("#rank_id").val($(this).data('rank'))
            $("#type").val($(this).data('type'))
        });
    })
    document.getElementById('Combinations').style.display = "block";
    function openCity(evt, cityName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>
{% endblock %}